### ISSUE TITLE
フラッシュメッセージが実装できない

### ISSUE THREAD

**Issue by ozeryu7** [ozeryu7/tenkue-board-r006#10]
Trello のuser新規登録のタスクの「formにエラーメッセージを追加」について、
フラッシュメッセージかと思いますが、application.scss、applicaton.htmlに
コードしてみましたが、どうもうまく表示できません。
実装したい機能は以下です。
・新規登録が完了したら→「アカウント登録が完了しました」（背景青色、文字白色）
・ログインしたら→「ログインしました」（背景青色、文字白色）
・ログアウトしたら→「ログアウトしました」（背景青色、文字白色）
ご助言いただけますと幸甚です。

今、users.controllerの追記をすればいいと分かり、取組中です。
違いましたらご指摘ください。

**Comment by msgyu** [comment]
こちらの記事が参考になります。
また、別ブランチで日本語化しているので、後回ししましょう
https://qiita.com/yamamoto11081/items/af3c64a430f0911e28fe

**Comment by ozeryu7** [comment]
コメントありがとうございます。
承知いたしました。
後回しにします。
